#!/bin/sh
# Gradle start up script for POSIX generated by Gradle.
APP_BASE_NAME=${0##*/}
APP_HOME=$( cd "${0%/*}" && pwd )

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

exec gradle "$@"
