openapi: 3.0.1
info:
  title: GitHub Repository Search API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /search:
    get:
      summary: Search GitHub repositories
      parameters:
        - name: q
          in: query
          description: Search query keyword(s)
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A JSON array of repository items
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        description:
                          type: string
                        url:
                          type: string
        '400':
          description: Missing q parameter
        '500':
          description: Internal server error

